credit_score:
  model:
    name: credit_score_model
  data:
    path: ./data/loan_data.csv
  features:
    num_cols:
      - person_age
      - person_income
      - person_emp_exp
      - loan_amnt
      - loan_int_rate
      - loan_percent_income
      - cb_person_cred_hist_length
    cat_cols:
      - person_gender
      - person_education
      - person_home_ownership
      - loan_intent
      - previous_loan_defaults_on_file
    target: loan_status
  steps_features:
    age_col: person_age
    lower_bound: 18
    upper_bound: 80
  discretizer:
    n_bins: 4
    strategy: kmeans
    encode: ordinal

loan_tenure:
  model:
    name: loan_tenure_model
  features:
    num_cols:
      - person_income
      - person_emp_exp
      - loan_amnt
      - cb_person_cred_hist_length
    cat_cols:
      - person_home_ownership
      - loan_intent
    target: tenure
  discretizer:
    n_bins: 3
    strategy: uniform
    encode: ordinal

general:
  random_state: 42
