credit_score:
  model:
    name: credit_score_model
  data:
    path: ./data/loan_data.csv
  features:
    num_cols:
      - person_age
      - person_income
      - person_emp_exp
      - loan_amnt
      - loan_int_rate
      - loan_percent_income
      - cb_person_cred_hist_length
    cat_cols:
      - person_gender
      - person_education
      - person_home_ownership
      - loan_intent
      - previous_loan_defaults_on_file
    target: loan_status
  steps_features:
    age_col: person_age
    lower_bound: 18
    upper_bound: 80
  discretizer:
    n_bins: 4
    strategy: kmeans
    encode: ordinal

loan_tenure:
  model:
    name: loan_tenure_model
  features:
    num_cols:
      - person_income
      - person_emp_exp
      - loan_amnt
      - cb_person_cred_hist_length
    cat_cols:
      - person_home_ownership
      - loan_intent
    target: tenure
  discretizer:
    n_bins: 3
    strategy: uniform
    encode: ordinal

estimators:
  classifier:
    RandomForestClassifier:
      n_estimators: 40 # 100
      criterion: gini
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
      max_features: sqrt
      max_leaf_nodes: null
    LogisticRegression:
      penalty: l2
      C: 1.0
      solver: lbfgs
      max_iter: 100
      multi_class: auto
    GradientBoostingClassifier:
      loss: log_loss
      learning_rate: 0.1
      n_estimators: 50
      criterion: friedman_mse
      min_samples_split: 2
      min_samples_leaf: 1
      max_depth: 3
      max_features: null # sqrt
      max_leaf_nodes: null

general:
  random_state: 42
  n_splits: 5
  test_size: 0.2
  current_size: 0.4
  model_selection:
    estimator_type: classifier
    estimator_name: GradientBoostingClassifier
