credit_score:
  model:
    name: credit_score_model
  features:
    - num_cols:
        - person_age
        - person_income
        - person_emp_exp
        - loan_amnt
        - loan_int_rate
        - loan_percent_income
        - cb_person_cred_hist_length
    - cat_cols:
        - person_gender
        - person_education
        - person_home_ownership
        - loan_intent
        - previous_loan_defaults_on_file

loan_tenure:
  model:
    name: loan_tenure_model
  features:
    - num_cols:
        - person_age
        - person_income
        - person_emp_exp
        - loan_amnt
        - loan_int_rate
        - loan_percent_income
        - cb_person_cred_hist_length
    - cat_cols:
        - person_gender
        - person_education
        - person_home_ownership
        - loan_intent
        - previous_loan_defaults_on_file
