[project]
name = "precisionlend"
version = "0.1.0"
description = "Machine Learning-Powered Loan Processing and Credit Scoring"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bentoml>=1.3.12",
    "mlflow>=2.17.2",
    "scikit-learn>=1.5.2",
    "zenml[server]==0.68.1",
]
